-
  name: demonstration of multiple task and command
  hosts: webservers
  tasks:
      -
        name: this is the first task
        command: sudo rm -rf /tmp/*
-
  name: this is the second task and command
  hosts: webservers
  tasks:
    -
      name: this is the second task and command
      command: mkdir -p /tmp/secondtask
    -
      name: this is the second command
      command: touch /tmp/secondtask/secondtask.txt






